export const LEAD_SCORE_THRESHOLDS = {
  OUTREACH_READY: 45,
  HIGH_PRIORITY: 65,
  STRONG_SCORE: 70,
  MEDIUM_SCORE: 40,
  LOW_RANGE_MIN: 0,
  LOW_RANGE_MAX: 20,
  MEDIUM_RANGE_MIN: 21,
  MEDIUM_RANGE_MAX: 40,
  GOOD_RANGE_MIN: 41,
  GOOD_RANGE_MAX: 60,
  EXCELLENT_RANGE_MIN: 61,
} as const;
